name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: These are some simple guidelines for creating a bug report, make sure your bug report follows all of these guidelines before submitting
      options:
        - label: This is an issue for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to report an issue with Hyperchat.
          required: true
        - label: This is an issue for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to report issues for those platforms.
          required: true
        - label: This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
          required: true
        - label: I have checked for a duplicate or similar issue. I made sure to check closed issues as well. 
          required: true
        - label: I am still able to reproduce the issue after I reinstall the extension.
          required: true
        - label: I have clear instructions to reproduce the bug, even on another machine.
          required: true
        - label: I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
          required: true
